### ISSUE TITLE
Publish the module in luarocks

### ISSUE THREAD

**Issue by ayoubfaouzi** [2dengine/profile.lua#1]
Hello @2dengine 

Would be nice having this module in luarocks so I can install it with the rest of the dependencies without linking it manually in src code.

Cheers.

**Comment by 2dengine** [comment]
Hello and thank you for the suggestion.
This is a standalone module (just a single file called "profile.lua") without any dependencies at all.
I will look into Luarocks, but cannot promise anything at the moment.

**Comment by 2dengine** [comment]
Upon further investigation it appears that Luarocks is affiliated with Lapis/MoonScript/itch.io and is NOT an "autonomous" service. The MIT License should allow you to publish profile.lua on there if you want, although we have absolutely no interest in Luarocks

**Comment by ayoubfaouzi** [comment]
Thank you so much @2dengine for your feedback, fair enough. Cheers.
