### ISSUE TITLE
document the meaning of the "time" column

### ISSUE THREAD

**Issue by lolbinarycat** [2dengine/profile.lua#2]
the unix time(1) command measures execution in several different ways:

* userspace time
* system time
* realtime

it is not immediately obvious which one is being used here.  it is also not obvious if it is using total execution time or average (tho looking at the code reveals it is using total time)

**Comment by 2dengine** [comment]
Hello and thank you for using the library.
Yes, the "time" in this case refers to the "total execution time".
Good point, I will change the documentation as requested in the next update.
